FROM jupyter/datascience-notebook

#USER root
#ENV DEBCONF_NOWARNINGS yes
#RUN apt-get update
#RUN apt-get install -y libpq-dev
#USER jovyan
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --no-cache-dir ipython-sql
#RUN pip install --no-cache-dir psycopg2==2.8.5
RUN pip install --no-cache-dir imblearn #==0.0
RUN pip install --no-cache-dir mysql-connector-python
RUN pip install --no-cache-dir sshtunnel
#RUN Rscript -e "install.packages(c('DBI', 'RPostgreSQL', 'rsample'), dependencies = TRUE, error = TRUE, repos='https://cran.r-project.org')"
