version: "3"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    image: mbuto/datascience-test
    container_name: my_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./docker/jupyter:/home/jovyan/work
      - /Volumes/GoogleDrive/マイドライブ/develop:/home/jovyan/csv
    command: 
      - start-notebook.sh --NotebookApp.token=''
