FROM jupyter/scipy-notebook

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --no-cache-dir ipython-sql
RUN pip install --no-cache-dir imblearn
RUN pip install --no-cache-dir mysql-connector-python
RUN pip install --no-cache-dir sshtunnel
RUN pip install --no-cache-dir openpyxl